"""add sequence to authors

Revision ID: 0ca7132de356
Revises: acef0251556e
Create Date: 2024-10-13 13:11:43.003859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ca7132de356'
down_revision: Union[str, None] = 'acef0251556e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('author', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('awards', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('characters', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('genre', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('genre', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('characters', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('awards', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('author', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
