"""maj1

Revision ID: 2ea1e2809794
Revises: b86868921c84
Create Date: 2024-10-10 23:16:19.346311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ea1e2809794'
down_revision: Union[str, None] = 'b86868921c84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'book_id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=100000),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'book_id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, on_null=False, start=1, increment=1, minvalue=1, maxvalue=9999999999999999999999999999, cycle=False, cache=20, order=False),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
