"""Modify book_id column type

Revision ID: 40d3174f5246
Revises: 9c8069f531d2
Create Date: 2024-10-13 12:24:08.519894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40d3174f5246'
down_revision: Union[str, None] = '9c8069f531d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('borrows', 'book_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_foreign_key(None, 'borrows', 'books', ['book_id'], ['book_id'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'borrows', type_='foreignkey')
    op.alter_column('borrows', 'book_id',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
