"""create tables

Revision ID: 9c8069f531d2
Revises: 5be46905780b
Create Date: 2024-10-13 12:20:12.212464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c8069f531d2'
down_revision: Union[str, None] = '5be46905780b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('series', sa.String(length=1000), nullable=True),
    sa.Column('description', sa.String(length=4000), nullable=True),
    sa.Column('language', sa.String(length=200), nullable=True),
    sa.Column('isbn', sa.String(length=100), nullable=True),
    sa.Column('book_format', sa.String(length=200), nullable=True),
    sa.Column('edition', sa.String(length=1000), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('publisher', sa.String(length=500), nullable=True),
    sa.Column('publish_date', sa.Date(), nullable=True),
    sa.Column('first_publish_date', sa.Date(), nullable=True),
    sa.Column('cover_image_url', sa.String(length=200), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id')
    )
    op.create_table('author',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('book_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('awards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('award', sa.String(length=500), nullable=True),
    sa.Column('book_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character', sa.String(length=200), nullable=True),
    sa.Column('book_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genre',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('genre', sa.String(length=200), nullable=True),
    sa.Column('book_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('borrows', 'book_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_foreign_key(None, 'borrows', 'books', ['book_id'], ['book_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'borrows', type_='foreignkey')
    op.alter_column('borrows', 'book_id',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_table('genre')
    op.drop_table('characters')
    op.drop_table('awards')
    op.drop_table('author')
    op.drop_table('books')
    # ### end Alembic commands ###
