"""add role to author

Revision ID: ada9f7bc3781
Revises: 40d3174f5246
Create Date: 2024-10-13 12:29:28.379454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ada9f7bc3781'
down_revision: Union[str, None] = '40d3174f5246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('role', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author', 'role')
    # ### end Alembic commands ###
