"""ajout tables

Revision ID: b86868921c84
Revises: 011c9ea6a06c
Create Date: 2024-10-04 15:50:25.529503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b86868921c84'
down_revision: Union[str, None] = '011c9ea6a06c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating',
    sa.Column('book_id', sa.INTEGER(), nullable=False),
    sa.Column('rating', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('num_ratings', sa.INTEGER(), nullable=True),
    sa.Column('like_percent', sa.DOUBLE_PRECISION(), nullable=True),
    sa.PrimaryKeyConstraint('book_id', name='sys_c008378')
    )
    # ### end Alembic commands ###
